from __future__ import annotations

"""Declarative job targeting profiles and competency triggers."""

# Signal definitions for resume selection and targeting
PRESALES_SIGNALS = {
    "demo",
    "demos",
    "discovery",
    "solution consulting",
    "solutions consulting",
    "solution consultant",
    "solutions consultant",
    "pre-sales",
    "presales",
    "sales engineer",
    "solutions engineer",
    "revenue retention",
    "retention",
    "expansion",
    "account growth",
}

SIMPLE_COMPETENCY_KEYWORDS = (
    ("Agile Project Management", ("agile", "project management")),
    ("Conversational AI and Chatbot Configuration", ("chatbot", "chatbots", "ai agent", "ai agents", "conversational ai")),
    ("NLP-based Messaging Workflows", ("natural language processing", "nlp", "ai performance metrics")),
    ("LivePerson LiveEngage", ("liveperson", "liveengage", "customer service platform")),
    ("Change Enablement", ("change enablement", "change efforts", "enterprise change", "change initiatives")),
    ("Adoption Strategy", ("adoption", "sustained adoption", "user adoption")),
    ("Adoption Measurement", ("adoption measures", "effectiveness measures", "feedback and data")),
    ("Account Health Management", ("account health", "health score", "customer health")),
    ("Success Planning", ("success plan", "success planning")),
    ("Value Realization", ("value realization", "business value", "roi")),
    ("Renewal Risk Management", ("renewal", "renewals", "retention")),
    ("Expansion Discovery", ("expansion", "upsell", "cross-sell", "account growth")),
    ("Executive Business Reviews", ("ebr", "ebrs", "executive business review", "executive business reviews", "qbr", "qbrs")),
    ("Organizational Readiness", ("organizational readiness", "change readiness", "readiness")),
    ("Customer Delivery", ("customer delivery", "customer-facing delivery", "client-facing delivery")),
    ("Service Delivery", ("service delivery",)),
    ("Process Documentation", ("process documentation", "document processes", "workflow documentation")),
    ("Comprehensive Training", ("comprehensive training", "comprehensive training plans", "training plans", "train end users", "end-user training", "user enablement")),
    ("Analytics and Reporting", ("analytics & reporting", "analytics and reporting", "analytics reporting")),
    ("Scope Management", ("scope",)),
    ("Resource Management", ("resource management", "internal resources")),
    ("Deliverable Management", ("deliverable", "deliverables")),
    ("Requirements Gathering", ("requirements gathering",)),
    ("Gap Analysis", ("gap analysis",)),
    ("Data Analysis", ("data analysis",)),
    ("Data Management", ("data management", "data guru", "etl", "data transformation", "model preparation")),
    ("Project Delivery", ("project delivery", "project deliverables", "delivery timeliness")),
    ("Model Quality", ("model quality", "modeling readiness", "validate inputs", "validation of advanced modeling assumptions")),
    ("Workflow Validation", ("validation", "validity", "drift detection", "quality review")),
    ("Continuous Improvement", ("continuous improvement", "ongoing monitoring", "monitoring")),
    ("AI-Assisted Workflows", ("ai-assisted", "ai-guided", "agentic", "intelligent systems")),
    ("Retention Analytics", ("retention", "renewal risk", "churn", "retention analytics")),
    ("Curated Reporting", ("curated reporting",)),
    ("Data-Driven Decision Support", ("data-driven", "decision support", "decision-making", "decision making")),
    ("Client Interfacing", ("client interfacing",)),
    ("Stakeholder Communication", ("stakeholder communication",)),
    ("Presentation Skills", ("presentation skills", "presentation")),
    ("Billing Operations", ("billing",)),
    ("Order Management", ("order management",)),
)

CONDITIONAL_COMPETENCY_ITEMS = {
    "pre sales and solution consulting": ("pre-sales", "presales", "solution consulting", "sales engineer", "demo", "demos"),
    "supply chain and manufacturing operations": ("supply chain", "manufacturing", "warehouse", "fulfillment", "inventory management", "inventory control"),
    "tableau": ("tableau", "analytics", "dashboard", "data analysis", "reporting"),
    "sap crystal reports": ("crystal reports", "sap", "reporting", "analytics"),
}

TARGETING_LANES = (
    {
        "key": "change_enablement",
        "label": "Change Enablement and Adoption",
        "signals": (
            "change enablement",
            "change management",
            "culture",
            "values",
            "organizational effectiveness",
            "enterprise transformation",
            "ai strategy",
            "ai integration",
            "future-of-work",
            "future of work",
            "operating model",
            "adoption",
            "resistance",
            "team member experience",
        ),
        "problem": "technology-enabled change adoption, stakeholder alignment, and resistance risk",
        "audience": "senior leaders, managers, cross-functional partners, and end users",
        "outcomes": ("sustained adoption", "trust", "workflow adoption", "measurable change"),
    },
    {
        "key": "presales_solution",
        "label": "Pre-Sales and Solution Consulting",
        "signals": (
            "pre-sales",
            "presales",
            "solution consulting",
            "solutions consulting",
            "solution consultant",
            "solutions consultant",
            "sales engineer",
            "sales engineering",
            "solutions engineer",
            "demo",
            "demos",
            "discovery",
            "value selling",
            "roi",
            "executive buyers",
        ),
        "problem": "client discovery, solution design, value alignment, and executive buying risk",
        "audience": "prospects, sales teams, executives, product teams, and implementation partners",
        "outcomes": ("qualified solutions", "client confidence", "revenue support", "implementation fit"),
    },
    {
        "key": "customer_success",
        "label": "Customer Success and Retention",
        "signals": (
            "customer success",
            "client success",
            "renewal",
            "retention",
            "expansion",
            "book of business",
            "arr",
            "nrr",
            "grr",
            "churn",
            "adoption",
            "qbr",
        ),
        "problem": "customer adoption, account risk, retention, and expansion pressure",
        "audience": "customers, executives, account teams, product teams, and support partners",
        "outcomes": ("retention", "account recovery", "adoption", "customer confidence"),
    },
    {
        "key": "implementation_delivery",
        "label": "Implementation and Delivery",
        "signals": (
            "implementation",
            "go-live",
            "configuration",
            "data migration",
            "integration",
            "hypercare",
            "project management",
            "scope",
            "deliverables",
            "timeline",
            "requirements",
        ),
        "problem": "implementation scope, technical complexity, timeline risk, and adoption readiness",
        "audience": "clients, project teams, executives, operations, and technical stakeholders",
        "outcomes": ("go-live readiness", "delivery quality", "risk reduction", "user adoption"),
    },
    {
        "key": "analytics_operations",
        "label": "Analytics and Operations",
        "signals": (
            "analytics",
            "data analysis",
            "dashboard",
            "kpi",
            "reporting",
            "forecast",
            "operational efficiency",
            "process improvement",
            "business intelligence",
        ),
        "problem": "data visibility, operational decision-making, process gaps, and performance risk",
        "audience": "executives, operations leaders, customer teams, and cross-functional partners",
        "outcomes": ("visibility", "decision support", "efficiency", "process improvement"),
    },
)

EMPLOYER_CONTEXTS = (
    {
        "key": "consulting",
        "signals": (
            "consulting firm",
            "advisory",
            "professional services",
            "client service",
            "client-facing",
            "consulting engagement",
            "consulting practice",
            "consultant",
            "consulting",
        ),
        "summary": "Fits consulting work where structured discovery, executive-ready decisions, and implementation credibility matter as much as the recommendation.",
        "competencies": ("Client Advisory", "Consulting Delivery"),
    },
    {
        "key": "saas",
        "signals": (
            "saas",
            "software as a service",
            "cloud platform",
            "platform",
            "subscription",
            "product-led",
            "software company",
            "software customers",
        ),
        "summary": "Fits SaaS teams that need customer problems translated into adoption, implementation quality, product feedback, and retention confidence.",
        "competencies": ("SaaS Customer Lifecycle", "Product Adoption"),
    },
    {
        "key": "healthcare",
        "signals": (
            "healthcare",
            "health care",
            "payer",
            "provider",
            "patient",
            "clinical",
            "claims",
            "medicaid",
            "medicare",
            "health plan",
        ),
        "summary": "Fits healthcare technology work where clearer workflows, adoption, reporting, and risk control affect service quality.",
        "competencies": ("Healthcare Technology Operations", "Workflow Adoption"),
    },
    {
        "key": "manufacturing",
        "signals": (
            "manufacturing",
            "supply chain",
            "warehouse",
            "inventory management",
            "inventory control",
            "distribution",
            "procurement",
            "production planning",
            "production line",
            "finance operations",
        ),
        "summary": "Fits operations-heavy environments where ERP, reporting, process control, and adoption have to support manufacturing, supply chain, and finance decisions.",
        "competencies": ("Manufacturing ERP", "Supply Chain Operations"),
    },
    {
        "key": "construction_engineering",
        "signals": (
            "construction",
            "engineering",
            "engineering and construction",
            "contractor",
            "project-based",
            "project based",
            "aec",
            "architecture",
            "field service",
            "capital projects",
            "project accounting",
        ),
        "summary": "Fits project-based construction and engineering delivery where ERP configuration, financial controls, and adoption have to hold up across projects, phases, and field operations.",
        "competencies": ("Project-Based ERP", "Client-Side Delivery"),
    },
    {
        "key": "financial_services",
        "signals": (
            "financial services",
            "banking",
            "payments",
            "fintech",
            "insurance",
            "risk management",
            "compliance",
            "audit",
            "controls",
        ),
        "summary": "Fits risk-aware technology work where process discipline, stakeholder alignment, and trustworthy reporting shape operating confidence.",
        "competencies": ("Risk-Aware Delivery", "Controls and Reporting"),
    },
    {
        "key": "education_assessment",
        "signals": (
            "school assessment",
            "assessment item",
            "assessment and learning",
            "measurement and learning",
            "learning systems",
            "learner-facing",
            "instructional",
            "k-12",
            "psychometric",
            "psychometrics",
            "educational measurement",
            "constructed-response",
            "technology-enhanced items",
            "tei",
            "academic content standards",
        ),
        "summary": "Fits education and assessment work where workflow validation, quality monitoring, and cross-functional coordination shape whether AI-assisted outputs can be trusted.",
        "competencies": ("Workflow Validation", "Continuous Improvement"),
    },
    {
        "key": "customer_experience",
        "signals": (
            "customer experience",
            "cx",
            "contact center",
            "ccaas",
            "ucaas",
            "voice",
            "chat",
            "messaging",
            "customer engagement",
        ),
        "summary": "Fits customer-experience technology work where discovery, workflow design, adoption, and analytics turn service friction into clearer operating choices.",
        "competencies": ("Customer Experience Technology", "Contact Center Workflows"),
    },
    {
        "key": "analytics_operations",
        "signals": (
            "analytics",
            "business intelligence",
            "reporting",
            "dashboard",
            "kpi",
            "data analysis",
            "operational efficiency",
            "process improvement",
        ),
        "summary": "Fits operations and analytics work where clearer data, workflow design, and stakeholder alignment improve decision quality.",
        "competencies": ("Business Intelligence", "Operational Analytics"),
    },
)

STORY_LENSES = (
    {
        "key": "consulting",
        "signals": ("consulting", "consultant", "advisory", "professional services", "client service", "engagement", "practice"),
        "identity": "client impact over slideware",
        "business_problem": "ambiguous client problems that need structure, trust, analysis, and measurable action",
        "candidate_story": "international client portfolio, executive workshops, ERP delivery, dashboards, and account recovery",
        "resume_context": "Brings a consulting-style record of entering ambiguous client environments, clarifying the problem, aligning stakeholders, and staying close enough to execution for recommendations to become measurable outcomes.",
        "cover_opening": "What drew me to {company_name} is the chance to do work where structured thinking has to become client impact. My strongest work has lived past the recommendation: clarifying the problem, aligning stakeholders, and staying close enough to implementation to make the outcome real.",
        "cover_lesson": "The consulting pattern in my background is straightforward: enter the ambiguity, structure the problem, earn trust quickly, and produce something the client can measure.",
        "interview_lens": "Speak like a consultant: state the answer first, define the client problem, show the structure, name tradeoffs, and connect the recommendation to implementation reality.",
    },
    {
        "key": "saas",
        "signals": ("saas", "software as a service", "cloud platform", "subscription", "product-led", "software company", "software customers"),
        "identity": "customer value after purchase",
        "business_problem": "turning software adoption, product feedback, and implementation quality into retention and expansion confidence",
        "candidate_story": "80+ customer portfolio, post-go-live adoption, QBRs, product/development triage, and $1M+ account stabilization",
        "resume_context": "Turns customer friction into adoption plans, product feedback, implementation quality, retention risk reduction, and scalable customer outcomes.",
        "cover_opening": "What drew me to {company_name} is the way this role sits after the sale, where software value either becomes real for customers or quietly turns into adoption and retention risk.",
        "cover_lesson": "In SaaS environments, I have learned to start with the customer workflow, make risk visible early, align product and delivery teams, and turn adoption into measurable value.",
        "interview_lens": "Speak to customer lifecycle value: adoption, account health, product feedback, retention risk, expansion discovery, and implementation quality.",
    },
    {
        "key": "healthcare",
        "signals": ("healthcare", "health care", "payer", "provider", "patient", "clinical", "claims", "medicaid", "medicare", "health plan"),
        "identity": "workflow clarity with service and risk consequences",
        "business_problem": "making complex technology workflows reliable enough for stakeholders who cannot afford confusion, delay, or poor visibility",
        "candidate_story": "ERP workflow ownership, reporting discipline, adoption support, risk control, and stakeholder alignment",
        "resume_context": "Brings workflow clarity, adoption support, reporting discipline, and risk-aware validation to environments where service quality depends on execution detail.",
        "cover_opening": "What drew me to {company_name} is the practical pressure behind this work: technology has to make workflows clearer, decisions easier, and service quality more reliable.",
        "cover_lesson": "In healthcare-technology settings, the work I understand best is practical and risk-aware: clarify the workflow, validate the data, support adoption, and reduce issues before they reach the people depending on the process.",
        "interview_lens": "Speak to workflow clarity, reporting, adoption, service quality, risk control, and careful stakeholder validation.",
    },
    {
        "key": "manufacturing",
        "signals": ("manufacturing", "supply chain", "warehouse", "inventory management", "inventory control", "distribution", "procurement", "production planning", "production line", "finance operations"),
        "identity": "systems work tied to physical operations",
        "business_problem": "keeping ERP, reporting, inventory, finance, and cross-site workflows aligned with operational reality",
        "candidate_story": "five-site ERP ownership, inventory automation, warehouse launch, reporting, training, and cross-functional adoption",
        "resume_context": "Connects ERP, inventory, reporting, finance operations, and cross-site adoption to practical operating decisions.",
        "cover_opening": "What drew me to {company_name} is the operational nature of the work: systems decisions have to hold up inside real manufacturing, supply chain, finance, and warehouse workflows.",
        "cover_lesson": "Manufacturing and supply-chain work shaped how I approach systems: map the workflow, validate it against operations, train the teams, and measure whether the process actually improved.",
        "interview_lens": "Speak to ERP, inventory, supply chain, finance operations, reporting, training, and cross-site adoption.",
    },
    {
        "key": "construction_engineering",
        "signals": ("construction", "engineering", "engineering and construction", "contractor", "project-based", "project based", "aec", "capital projects", "project accounting"),
        "identity": "systems delivery for project-based operations",
        "business_problem": "making ERP configuration, project accounting, and adoption reliable across projects, phases, and field teams",
        "candidate_story": "client-side ERP ownership, finance-facing close, migration delivery, and compliance-constrained go-live",
        "resume_context": "Brings client-side ERP ownership, finance partnership, and compliance-constrained delivery to project-based operations.",
        "cover_opening": "What drew me to {company_name} is the project-based reality of the work: ERP decisions have to hold up across projects, finance controls, and field execution.",
        "cover_lesson": "In project-based delivery, I map the workflow, protect the financial calendar, configure to the client's real constraints, and keep adoption moving after go-live.",
        "interview_lens": "Speak to client-side ERP ownership, project accounting, finance partnership, configuration discipline, and compliance-constrained go-live.",
    },
    {
        "key": "financial_services",
        "signals": ("financial services", "banking", "payments", "fintech", "insurance", "risk management", "compliance", "audit", "controls"),
        "identity": "trustworthy execution in risk-aware environments",
        "business_problem": "turning complex stakeholder, process, and reporting needs into controlled decisions people can trust",
        "candidate_story": "scope control, executive alignment, SQL validation, reporting, issue triage, and risk-aware implementation",
        "resume_context": "Brings process discipline, stakeholder governance, validation, and trustworthy reporting to technology work where confidence matters.",
        "cover_opening": "What drew me to {company_name} is the risk-aware nature of the work: the value is not just moving quickly, but creating decisions, reporting, and delivery practices people can trust.",
        "cover_lesson": "For risk-sensitive work, I bring the same discipline: make the risk visible, validate the data, clarify ownership, and create a path stakeholders can trust before execution scales.",
        "interview_lens": "Speak to risk-aware delivery, controls, governance, validation, stakeholder confidence, and trustworthy reporting.",
    },
    {
        "key": "education_assessment",
        "signals": ("school assessment", "assessment item", "assessment and learning", "measurement and learning", "learner-facing", "instructional", "k-12", "psychometric", "constructed-response", "academic content standards", "validity", "fairness", "accessibility"),
        "identity": "quality-sensitive workflows people can trust",
        "business_problem": "making AI-assisted assessment and learning workflows reliable enough for educators, partners, and learners to trust at scale",
        "candidate_story": "workflow validation, data quality, AI-assisted workflow improvement, stakeholder alignment, and measurable follow-through",
        "resume_context": "Brings workflow validation, data quality, stakeholder alignment, and measurable follow-through to environments where output quality has to hold up across content, technology, and operational teams.",
        "cover_opening": "What drew me to {company_name} is the quality standard behind the work: AI-assisted systems only matter when the workflow stays valid, measurable, and useful for the people depending on it.",
        "cover_lesson": "For education and assessment work, I would bring the same operating discipline I have used elsewhere: validate the workflow, make the quality criteria explicit, align the stakeholders, and keep continuous improvement grounded in usable evidence.",
        "interview_lens": "Speak to workflow validation, quality monitoring, stakeholder alignment, continuous improvement, and translating technical concepts into practical operating decisions.",
    },
    {
        "key": "customer_experience",
        "signals": ("customer experience", "cx", "contact center", "ccaas", "ucaas", "voice", "chat", "messaging", "customer engagement"),
        "identity": "turning service friction into better workflows",
        "business_problem": "connecting customer engagement workflows, analytics, and adoption so service teams can improve outcomes at scale",
        "candidate_story": "LivePerson workflows, SMS pilot support, customer interaction analytics, dashboards, and adoption support",
        "resume_context": "Turns service friction into clearer workflows, messaging configuration, analytics, adoption, and operating decisions.",
        "cover_opening": "What drew me to {company_name} is the customer-experience pressure behind the role: every workflow choice affects how quickly teams can understand, respond to, and improve customer interactions.",
        "cover_lesson": "The customer-experience side of my background is hands-on: study the interaction, configure the workflow, measure the friction, and help teams adopt a better way to serve customers.",
        "interview_lens": "Speak to service friction, workflow design, messaging/contact-center operations, customer analytics, and adoption.",
    },
    {
        "key": "analytics_operations",
        "signals": ("analytics", "business intelligence", "reporting", "dashboard", "kpi", "data analysis", "operational efficiency", "process improvement"),
        "identity": "turning messy data into operating decisions",
        "business_problem": "converting reporting gaps, performance signals, and workflow questions into decisions leaders can act on",
        "candidate_story": "200+ dashboards, SQL/Power BI/Crystal reporting, KPI development, operational analysis, and executive visibility",
        "resume_context": "Converts messy operational data into dashboards, KPI visibility, process improvements, and decisions leaders can act on.",
        "cover_opening": "What drew me to {company_name} is the decision-making core of the role: data only matters when it changes priorities, clarifies tradeoffs, or improves how teams operate.",
        "cover_lesson": "On analytics work, I start with the decision first, build the reporting around it, and make the output usable enough to change the work.",
        "interview_lens": "Speak to decision quality, KPI visibility, operational tradeoffs, workflow improvement, and measurable action from reporting.",
    },
)

BRIDGE_EVIDENCE_AREAS = (
    {
        "label": "Consulting and Structured Problem Solving",
        "job_terms": (
            "management consulting",
            "strategy consulting",
            "consulting firm",
            "advisory",
            "case team",
            "case teams",
            "associate consultant",
            "associate consultants",
            "executive",
            "analyses",
        ),
        "resume_terms": (
            "structured discovery",
            "60+ executive workshops",
            "QBRs",
            "stakeholder alignment",
            "80+ manufacturing clients",
            "200+ dashboards",
            "risk-aware implementation plans",
        ),
        "safe_terms": (
            "client advisory",
            "structured problem solving",
            "executive stakeholder alignment",
        ),
    },
    {
        "label": "Change Adoption and Enablement",
        "job_terms": ("change", "adoption", "enablement", "resistance", "training", "communications", "transformation"),
        "resume_terms": ("change management", "role-based training", "adoption", "enablement materials", "training documentation", "adoption guides", "newsletters"),
        "safe_terms": ("change enablement", "adoption strategy", "change communications", "role-based training", "resistance management"),
    },
    {
        "label": "Client-Side ERP Ownership and Finance Partnership",
        "job_terms": (
            "controller",
            "cfo",
            "operations lead",
            "client side",
            "client-side",
            "sat on the client side",
            "lived through",
            "system change",
            "accounting",
            "finance",
        ),
        "resume_terms": (
            "plant controllers",
            "accounting managers",
            "cfo",
            "month-end",
            "year-end",
            "close",
            "audit readiness",
            "owned aptean intuitive",
            "five sites",
        ),
        "safe_terms": (
            "client-side ERP ownership",
            "finance-facing implementation",
            "CFO and controller partnership",
        ),
    },
    {
        "label": "Executive Stakeholder Alignment",
        "job_terms": ("executive", "senior leaders", "influence", "stakeholder", "relationships", "leadership"),
        "resume_terms": ("60+ executive workshops", "directors", "VPs", "executive leadership", "stakeholder alignment"),
        "safe_terms": ("executive stakeholder alignment", "leader enablement", "cross-functional influence"),
    },
    {
        "label": "AI-Assisted Workflow Improvement",
        "job_terms": (
            "ai",
            "artificial intelligence",
            "ai strategy",
            "ai integration",
            "ai-driven",
            "ai agent",
            "ai agents",
            "chatbot",
            "chatbots",
            "natural language processing",
            "nlp",
            "knowledge base",
            "tone customization",
        ),
        "resume_terms": (
            "AI tools",
            "AI-Assisted Documentation",
            "Generative AI",
            "AI-assisted",
            "LivePerson",
            "LiveEngage",
            "chat",
            "text workflows",
            "automated greetings",
            "NLP-based Messaging",
            "Conversational AI",
            "Chatbot Configuration",
        ),
        "safe_terms": (
            "AI-assisted workflow improvement",
            "AI-assisted documentation",
            "practical AI adoption support",
            "conversational AI configuration",
            "chatbot workflow automation",
            "LivePerson LiveEngage",
        ),
    },
    {
        "label": "Implementation Delivery",
        "job_terms": ("implementation", "go-live", "configuration", "integration", "data migration", "scope", "requirements"),
        "resume_terms": ("full lifecycle", "go-live", "configuration", "data migration", "integration", "requirements definition", "SOW"),
        "safe_terms": ("full lifecycle implementation", "go-live readiness", "scope alignment"),
    },
    {
        "label": "Risk and Escalation Management",
        "job_terms": ("risk", "escalation", "ambiguity", "complex", "prioritize", "mitigate"),
        "resume_terms": ("risk", "escalation", "$1M+", "at-risk accounts", "issue triage"),
        "safe_terms": ("risk mitigation", "issue triage", "account recovery"),
    },
    {
        "label": "Metrics and Decision Support",
        "job_terms": ("metrics", "measures", "feedback", "data", "kpi", "effectiveness", "reporting"),
        "resume_terms": ("200+ dashboards", "KPI", "Power BI", "SQL", "reporting", "data analysis"),
        "safe_terms": ("adoption measurement", "KPI reporting", "data-informed decision support"),
    },
    {
        "label": "Customer and Revenue Outcomes",
        "job_terms": ("customer", "client", "revenue", "retention", "expansion", "satisfaction", "qbr"),
        "resume_terms": ("80+ international", "$1M+", "QBR", "customer-facing", "client-facing", "retention"),
        "safe_terms": ("customer adoption", "account recovery", "executive business reviews"),
    },
    {
        "label": "Product Ownership and Agile Delivery Partnership",
        "job_terms": (
            "product owner",
            "product manager",
            "product management",
            "agile",
            "scrum",
            "backlog",
            "sprint",
            "roadmap",
            "user research",
        ),
        "resume_terms": (
            "Product Management and Product Ownership",
            "Agile development team",
            "de facto product owner",
            "backlog-ready requirements",
            "roadmap",
            "stakeholder requirements gathering",
        ),
        "safe_terms": (
            "Agile delivery team partnership",
            "product ownership scope",
            "backlog prioritization",
            "roadmap ownership",
            "structured user feedback synthesis",
        ),
    },
    {
        "label": "Project-Based ERP Delivery",
        "job_terms": (
            "construction",
            "engineering",
            "project accounting",
            "job cost",
            "job costing",
            "field teams",
            "capital projects",
            "project-based",
            "project based",
        ),
        "resume_terms": (
            "cost/timeline options",
            "vendor tradeoffs",
            "go-live",
            "requirements",
            "cross-site training",
            "audit readiness",
            "month-end",
        ),
        "safe_terms": (
            "project-based ERP delivery",
            "finance-aware configuration",
            "cross-functional implementation planning",
        ),
    },
)

UNSUPPORTED_REQUIREMENT_PATTERNS = (
    ("Values Activation", ("values activation", "company values", "values are experienced", "bring our company values to life")),
    ("Culture Transformation", ("culture transformation", "organizational culture", "how culture evolves", "culture evolves")),
    ("Enterprise AI Strategy Ownership", ("enterprise ai strategy", "own ai strategy", "lead ai strategy", "ai operating model")),
    ("People and Culture Partnership", ("people & culture", "people and culture", "learning & development", "internal communications", "organizational culture")),
    ("HR Policy Ownership", ("hr policies", "people policy", "employee policy", "human resources policy")),
    ("Legal or Compliance Program Ownership", ("compliance program", "compliance framework", "regulatory compliance program", "legal review", "policy governance", "compliance disclosure")),
    ("DEI Governance Ownership", ("dei governance", "dei strategy", "dei principles", "inclusion strategy")),
    ("Enterprise AI Ethics or Disclosure Ownership", ("ai ethics", "ai disclosure", "responsible ai policy", "ai governance")),
    ("Advanced API Authentication Ownership", ("api integrations", "endpoint configuration", "authentication", "tokens", "jwt", "secure connections")),
    ("Operating Model or Future-of-Work Leadership", ("operating model", "future-of-work", "future of work", "leadership transitions")),
    ("People Manager Enablement", ("equip senior leaders", "people managers")),
    ("Direct People Leadership", ("lead a team of", "direct reports", "manage a team")),
)

POOR_FIT_REQUIREMENT_AREAS = (
    {
        "label": "Formal IT Department Leadership",
        "job_terms": (
            "it leader",
            "it manager",
            "director of it",
            "head of it",
            "it leadership",
            "lead the it",
            "information technology leader",
            "technology leader",
            "direct reports",
            "people manager",
            "manage a team",
            "it budget",
            "technology budget",
            "service desk",
            "help desk",
            "infrastructure",
            "network",
            "cybersecurity",
            "security governance",
            "application portfolio",
        ),
        "resume_terms": (
            "direct reports",
            "managed a team",
            "people manager",
            "it budget",
            "technology budget",
            "cybersecurity",
            "security governance",
            "service desk",
            "help desk",
            "infrastructure",
            "network",
            "application portfolio",
        ),
        "minimum_job_hits": 3,
    },
    {
        "label": "Advanced Software Engineering Ownership",
        "job_terms": (
            "software engineer",
            "software development",
            "write code",
            "coding",
            "python",
            "java",
            "c#",
            "typescript",
            "react",
            "microservices",
            "api development",
            "full stack",
        ),
        "resume_terms": (
            "software engineer",
            "software development",
            "python",
            "java",
            "c#",
            "typescript",
            "react",
            "microservices",
            "api development",
            "full stack",
        ),
        "minimum_job_hits": 4,
    },
    {
        "label": "Deep Supply Chain Optimization Specialty",
        "job_terms": (
            "network optimization",
            "supply chain optimization",
            "transportation modeling",
            "linear programming",
            "optimization model",
            "s&op",
            "demand planning",
            "supply planning",
            "inventory optimization",
        ),
        "resume_terms": (
            "network optimization",
            "transportation modeling",
            "linear programming",
            "optimization model",
            "demand planning",
            "supply planning",
            "inventory optimization",
        ),
        "minimum_job_hits": 3,
    },
)

SPECIALTY_GAP_AREAS = (
    {
        "label": "Benefits Administration Domain",
        "job_terms": (
            "benefit implementation",
            "benefit implementations",
            "benefit administration",
            "employee benefits",
            "benefit configuration",
            "eligibility rules",
            "carrier connections",
            "open enrollment",
            "retirement plans",
            "health insurance",
        ),
        "resume_terms": (
            "benefit implementation",
            "benefit administration",
            "employee benefits",
            "benefit configuration",
            "eligibility rules",
            "carrier connections",
            "open enrollment",
            "retirement plans",
            "health insurance",
        ),
        "minimum_job_hits": 2,
    },
    {
        "label": "Payroll and HR Platform Domain",
        "job_terms": (
            "payroll",
            "prismhr",
            "hcm",
            "hris",
            "human resources",
            "hr technology",
            "benefits administration systems",
            "employee records",
        ),
        "resume_terms": (
            "payroll",
            "prismhr",
            "hcm",
            "hris",
            "human resources",
            "hr technology",
            "benefits administration system",
            "employee records",
        ),
        "minimum_job_hits": 2,
    },
    {
        "label": "Benefits Regulatory and Compliance Domain",
        "job_terms": (
            "federal and state regulations",
            "benefit administration compliance",
            "benefits compliance",
            "employee benefits regulations",
            "cobra",
            "aca",
            "erisa",
            "regulatory scenarios",
        ),
        "resume_terms": (
            "benefits compliance",
            "benefit administration compliance",
            "employee benefits regulations",
            "cobra",
            "aca",
            "erisa",
            "regulatory scenarios",
        ),
        "minimum_job_hits": 1,
    },
)

TAILORING_EMPHASIS_PROFILES = (
    {
        "key": "launch_migration",
        "label": "Launch and Migration Proof",
        "signals": (
            "go-live",
            "launch",
            "warehouse",
            "amazon robotics",
            "migration",
            "cutover",
            "uat",
            "testing",
            "data migration",
            "implementation",
        ),
        "lanes": ("implementation_delivery", "analytics_operations", "change_enablement"),
        "employer_contexts": ("manufacturing", "consulting"),
        "summary_family": "builder",
        "proof_anchor": "launch",
        "bullet_terms": (
            "warehouse",
            "amazon robotics",
            "go-live",
            "launch",
            "migration",
            "uat",
            "testing",
            "etl",
            "sql",
            "inventory",
            "78%",
            "22%",
        ),
        "competency_terms": (
            "Project Delivery",
            "Requirements Gathering",
            "Gap Analysis",
            "Data Management",
            "Workflow Validation",
        ),
    },
    {
        "key": "analytics_reporting",
        "label": "Analytics and Reporting Proof",
        "signals": (
            "analytics",
            "reporting",
            "dashboard",
            "dashboards",
            "kpi",
            "sql",
            "power bi",
            "business intelligence",
            "decision support",
            "forecast",
        ),
        "lanes": ("analytics_operations", "implementation_delivery", "corporate_strategy"),
        "employer_contexts": ("manufacturing", "financial_services", "customer_experience"),
        "summary_family": "analytics",
        "proof_anchor": "dashboards",
        "bullet_terms": (
            "dashboard",
            "dashboards",
            "kpi",
            "sql",
            "crystal reports",
            "power bi",
            "forecast",
            "reporting",
            "decision",
            "visibility",
            "200+",
        ),
        "competency_terms": (
            "Analytics and Reporting",
            "Data Analysis",
            "Curated Reporting",
            "Data-Driven Decision Support",
            "Workflow Validation",
        ),
    },
    {
        "key": "customer_value",
        "label": "Customer Value and Revenue Proof",
        "signals": (
            "customer success",
            "renewal",
            "retention",
            "expansion",
            "book of business",
            "account growth",
            "qbr",
            "ebr",
            "revenue",
            "solution consulting",
            "demo",
            "discovery",
        ),
        "lanes": ("customer_success", "presales_solution", "implementation_delivery"),
        "employer_contexts": ("saas", "consulting"),
        "summary_family": "customer",
        "proof_anchor": "revenue",
        "bullet_terms": (
            "customer",
            "client",
            "renewal",
            "retention",
            "expansion",
            "revenue",
            "qbr",
            "executive",
            "discovery",
            "demo",
            "80+",
            "1m+",
            "6m+",
        ),
        "competency_terms": (
            "Account Health Management",
            "Executive Business Reviews",
            "Value Realization",
            "Renewal Risk Management",
            "Expansion Discovery",
        ),
    },
    {
        "key": "change_adoption",
        "label": "Change Adoption Proof",
        "signals": (
            "change",
            "adoption",
            "enablement",
            "training",
            "readiness",
            "communications",
            "stakeholder alignment",
            "organizational readiness",
            "transformation",
        ),
        "lanes": ("change_enablement", "implementation_delivery", "customer_success"),
        "employer_contexts": ("healthcare", "consulting", "manufacturing"),
        "summary_family": "change",
        "proof_anchor": "adoption",
        "bullet_terms": (
            "change",
            "adoption",
            "enablement",
            "training",
            "role-based",
            "readiness",
            "communications",
            "resistance",
            "stakeholder",
        ),
        "competency_terms": (
            "Change Enablement",
            "Adoption Strategy",
            "Organizational Readiness",
            "Comprehensive Training",
            "Workflow Validation",
        ),
    },
    {
        "key": "ai_workflows",
        "label": "AI and Workflow Automation Proof",
        "signals": (
            "ai",
            "automation",
            "llm",
            "agent",
            "agents",
            "generative",
            "chatbot",
            "conversational ai",
            "workflow automation",
            "enablement",
        ),
        "lanes": ("analytics_operations", "change_enablement", "presales_solution"),
        "employer_contexts": ("customer_experience", "saas", "consulting"),
        "summary_family": "modern",
        "proof_anchor": "ai",
        "bullet_terms": (
            "claude",
            "ai-assisted",
            "automation",
            "chatbot",
            "liveperson",
            "liveengage",
            "sms",
            "workflow",
            "documentation",
            "sql troubleshooting",
        ),
        "competency_terms": (
            "AI-Assisted Workflows",
            "Conversational AI and Chatbot Configuration",
            "NLP-based Messaging Workflows",
            "LivePerson LiveEngage",
            "Process Documentation",
        ),
    },
    {
        "key": "operations_strategy",
        "label": "Operations Strategy Proof",
        "signals": (
            "strategy",
            "recommendations",
            "decision-making",
            "stakeholder",
            "cross-functional",
            "procurement",
            "finance operations",
            "risk",
            "audit",
            "controls",
        ),
        "lanes": ("corporate_strategy", "analytics_operations", "implementation_delivery"),
        "employer_contexts": ("financial_services", "consulting", "manufacturing"),
        "summary_family": "operator",
        "proof_anchor": "decision",
        "bullet_terms": (
            "decision",
            "recommendations",
            "tradeoffs",
            "stakeholder",
            "executive",
            "workshop",
            "audit",
            "risk",
            "finance",
            "operations",
            "procurement",
        ),
        "competency_terms": (
            "Data-Driven Decision Support",
            "Stakeholder Communication",
            "Presentation Skills",
            "Project Delivery",
            "Process Documentation",
        ),
    },
)

SAME_COMPANY_OUTPUT_LOOKBACK = 20
SAME_COMPANY_VARIABLE_OVERLAP_THRESHOLD = 0.78


def _assert_required_keys(collection: tuple[dict[str, object], ...], required_keys: tuple[str, ...], config_name: str) -> None:
    for index, entry in enumerate(collection):
        assert isinstance(entry, dict), f"{config_name}[{index}] must be a dict"
        for key in required_keys:
            assert key in entry, f"{config_name}[{index}] missing required key: {key}"


_assert_required_keys(
    TARGETING_LANES,
    ("key", "label", "problem", "audience", "outcomes", "signals"),
    "TARGETING_LANES",
)
_assert_required_keys(
    BRIDGE_EVIDENCE_AREAS,
    ("label", "job_terms", "resume_terms", "safe_terms"),
    "BRIDGE_EVIDENCE_AREAS",
)
_assert_required_keys(
    POOR_FIT_REQUIREMENT_AREAS,
    ("label", "job_terms", "resume_terms", "minimum_job_hits"),
    "POOR_FIT_REQUIREMENT_AREAS",
)
_assert_required_keys(
    SPECIALTY_GAP_AREAS,
    ("label", "job_terms", "resume_terms", "minimum_job_hits"),
    "SPECIALTY_GAP_AREAS",
)
_assert_required_keys(
    STORY_LENSES,
    (
        "key",
        "signals",
        "identity",
        "business_problem",
        "candidate_story",
        "interview_lens",
        "resume_context",
        "cover_lesson",
    ),
    "STORY_LENSES",
)
_assert_required_keys(
    EMPLOYER_CONTEXTS,
    ("key", "signals", "summary", "competencies"),
    "EMPLOYER_CONTEXTS",
)
_assert_required_keys(
    TAILORING_EMPHASIS_PROFILES,
    (
        "key",
        "label",
        "signals",
        "lanes",
        "employer_contexts",
        "summary_family",
        "proof_anchor",
        "bullet_terms",
        "competency_terms",
    ),
    "TAILORING_EMPHASIS_PROFILES",
)
assert SAME_COMPANY_OUTPUT_LOOKBACK >= 1, "SAME_COMPANY_OUTPUT_LOOKBACK must be positive"
assert 0 < SAME_COMPANY_VARIABLE_OVERLAP_THRESHOLD < 1, (
    "SAME_COMPANY_VARIABLE_OVERLAP_THRESHOLD must be between 0 and 1"
)
